config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions: 'customer/sessions',
  passwords: 'customer/passwords',
  registrations: 'customer/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'customers/products#top'

  scope module: :customers do
  resources :products, only: [:show,:index]


  #resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy]

  get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  resources :orders, only: [:new, :create, :index, :show]

  delete 'cart_products' => 'cart_products#destroy_all', as: 'destroy_all'

  get 'product/about' => 'products#about', as: 'about'
  resources :products, only: [:show,:index], module: 'customers'
 # resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy,:destroy_all]
  resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]

  get 'searches' => 'search#search', as: 'search'

  get 'searches/products' => 'search#products', as: 'products_search'
  
  resources :customers do
    collection do
    get :quit
    patch :withdraw
  end



end
end
  namespace :customers do
    post 'orders/complete' => 'orders#complete', as: 'complete'
    #get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  end

  devise_for :admins, controllers: {
  sessions: 'admin/sessions',
  passwords: 'admin/passwords',
  registrations: 'admin/registrations'
  }
  namespace :admins do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :products, only:[:index, :new, :show, :edit, :create, :update]
    get 'top' => 'products#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :end_users, only: [:index, :show, :edit, :update]

  get 'searches' => 'search#search', as: 'search'

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum status: {"入金待ち": 0,"入金確認": 1,"制作中": 2,"発送準備中": 3,"発送済み": 4 }
  enum payment_methods: {"クレジットカード": 0,"銀行振込": 1 }
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

 def index
 end

 def show
 end

 def edit
 end

 def update
 end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    # @cart_products = current_customer.cart_products
    @order_details = @order.order_details
    @totalprice = @order_details.map{ |order_detail| order_detail.product.price * order_detail.amount}.inject(:+)
    #@cart_products = @order.cart_products
		#@order_detail = params[:making_status]
  end

  def index
    @orders = Order.all
    @order = params[:name]
    #@order_details = OrderDetails.all
    #@order_detail = OrdrDetail.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admins_orders_path
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

  def order_details_params
    params.require(:order_details).permit(:amount, :making_status)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
   before_action :reject_customer, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end




  protected

  def reject_customer

    if @customer = Customer.find_by(email: params[:customer][:email])
      if @customer.is_deleted == "退会済み"
        flash[:error] = "退会済みです。"
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def new
    @address = Address.new
  end

  def index
    @address = Address.new
    @addresses = current_customer.addresses
    # @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save!
    redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
     @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to  addresses_path, notice: ''
    else
      render 'edit'
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customers/cart_products_controller.rb
class Customers::CartProductsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_product = current_customer.cart_products
    if @cart_product.empty?
       @totalprice = 0
    else
       @totalprice = @cart_product.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+).to_s(:delimited)
    end
  end

  def create
    @cart_product = CartProduct.new(cart_product_params)
    @cart_product.customer_id = current_customer.id
    if @cart_product.save
    redirect_to cart_products_path
    else
      @product = Product.find(params[:cart_product][:product_id])
      @genres = Genre.all
      render 'customers/products/show'
    end
  end
  def update
    @cart_product = CartProduct.find(params[:id])
    if @cart_product.update(cart_product_params)
      redirect_to cart_products_path, notice: ''
    else
      render 'index'
    end
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to cart_products_path
  end

  def destroy_all
    @cart_product = current_customer.cart_products
    @cart_product.destroy_all
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to cart_products_path
  end

  private
    def cart_product_params
       params.require(:cart_product).permit(:product_id, :quantity)
    end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
     @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path, notice: ''
    else
      render 'edit'
    end
  end

  def withdraw
    current_customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def self.search(word)
  end

 private
    def customer_params
       params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
    end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  def new
    @order = Order.new
    @addresses = Address.all
  end

  def create
    @cart_products = current_customer.cart_products

    @order = Order.new(order_params)
    if params[:addresses] == "new_address"
      @address = Address.new
      @address.postal_code = @order.postal_code
      @address.address     = @order.address
      @address.name        = @order.name
      @address.customer_id = current_customer.id
      @address.save
    end

    if @order.save

    @cart_products.each do |cart_product|
      @order_detail = OrderDetail.new
      @order_detail.amount = cart_product.quantity
      @order_detail.price = cart_product.product.price
      @order_detail.order_id = @order.id
      @order_detail.product_id = cart_product.product.id
      @order_detail.save
    end
    redirect_to thanx_path
    else
      render '/customers/orders/complete'
    end

  end


  def complete
    @cart_products = current_customer.cart_products
    @totalprice = @cart_products.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+)
    @order = Order.new
    @order.customer_id = current_customer.id
    @order.total_payment = @totalprice
    if params[:order][:addresses] == "myaddress"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.address
      @order.name        = current_customer.last_name +
                          current_customer.first_name
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name
    elsif params[:order][:addresses] == "new_address"
      # @address = Address.new
      # @adress.postal_code = params[:order][:postal_code]
      # @adress.address     = params[:order][:address]
      # @adress.name        = params[:order][:name]
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

    end

  end

  def thanx
  end

  def index
    @orders = Order.all
    @cart_products = current_customer.cart_products
    @order_detail = current_customer.cart_products
  end

  def show
    @cart_products = current_customer.cart_products
    @totalprice = @cart_products.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+)
    @orders = Order.find(params[:id])
  end

  def thanx
  end


  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :payment_methods, :name, :total_payment, :shipping_cost, :status, :customer_id,  :address_id, :addresses )
  end

end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
  def top
    @product = Product.page(params[:page]).reverse_order
    @genres = Genre.all
  end

  def about
  end

  def index
    if params[:genre_id]
       @product = Product.where(genre_id: params[:genre_id]).page(params[:page]).reverse_order
       @genre_name = Genre.find(params[:genre_id]).name
    else
       @product = Product.page(params[:page]).reverse_order
       @genre_name = "商品"
    end
    @genres = Genre.all
  end

  def show
     @product = Product.find(params[:id])
     @cart_product = CartProduct.new
     @genres = Genre.all
  end
end

app/controllers/customers/search_controller.rb
class Customers::SearchController < ApplicationController
  before_action :authenticate_customer!

	def search
		@word = params[:search_word]
		method = params[:search_method]
		# model = params[:search_model]
		@products = Product.search(method,@word)
		# if model == 'Product'
	 #   @products = Product.search(method,@word)
	 # else
	 #   @products = Product.all
	 # end
	end

  def products
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @value).page(params[:page]).reverse_order
    @genres = Genre.all


    @genre = Genre.find_by(name: @value)

  end

  private

  def match(value)

    Product.where(name: value).or(Product.where(genre_id: value))
  end

  def forward(value)
    Product.where("name LIKE ?", "#{value}%")
  end

  def backward(value)
    Product.where("name LIKE ?", "%#{value}")
  end

  def partical(value)
    Product.where("name LIKE ?", "%#{value}%")
  end


  def search_for(how, value)
    case how
    when 'match'
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
     @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path, notice: ''
    else
      render 'edit'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_path
  end

 private
    def customer_params
       params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
    end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/orders/complete.html.erb
<div calss="row">
  <div class="col-xs-9">
    <h2 class="head-line title_h2 text-center">注文情報確認</h2>
      <%#= form_with model:@order, url: orders_path, method: :post, local:true do |f| %>
         <table class="table table-hover table-inverse table-bordered">
          <thead>
            <tr class="info">
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
            </tr>
          </thead>
          <tbody>
          <% @cart_products.each do |cart_product| %>
            <tr>
              <td class="text-left">
                <%= attachment_image_tag(cart_product.product, :image, size: "60x50", fallback: "no_image.jpg") %>
                <%= cart_product.product.name %>
              </td>
              <td class="text-right">
                <%= cart_product.product.price %>
              </td>
              <td class="text-right">
                <%= cart_product.quantity %>
              </td>
              <td class="text-right">
                <%= (cart_product.product.price * cart_product.quantity).to_s(:delimited) %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <div class="col-xs-3 billing">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">送料</th>
            <td class="text-right col-xs-5">800</td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-right"><%= @totalprice.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-right"><%= (@totalprice + 800).to_s(:delimited) %></td>
          </tr>
      </table>
      </div>
    <div class="col-xs-6 billing">
      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= @order.payment_methods %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= @order.postal_code + @order.address + @order.name %>
          </td>
        </tr>
      </table>

      <br><br><%#= link_to '購入を確定する', thanx_path, class: "btn btn-success" %>
    </div>
      <%# end %>
      <%= form_with model: @order, url: orders_path, method: :post, local:true do |f| %>
        <%= hidden_field_tag :addresses, params[:order][:addresses] %>
        <%= f.hidden_field :customer_id %>
        <%= f.hidden_field :postal_code %>
        <%= f.hidden_field :address %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :shipping_cost %>
        <%= f.hidden_field :total_payment %>
        <%= f.hidden_field :payment_methods %>
        <%= f.hidden_field :status %>
        <%= f.submit "購入を確定する", class: "btn btn-success" %>
      <% end %>
  </div>

app/views/customers/orders/index.html.erb
<div class="container">
  <div calss="row">
  	<div class="col-xs-8"><br><br><br><br>
        <h3 class="head-line title_h2"><span style="background-color: #afeeee">注文履歴一覧</span></h3>
					<table class="table table-hover table-bordered  table-condensed">
						<thead>
							<tr>
								<th>注文日</th>
								<th>配送先</th>
								<th>注文商品</th>
								<th>支払金額</th>
								<th>ステータス</th>
								<th>注文詳細</th>
							</tr>
						</thead>
						<tbody>
							<% @orders.each do |order| %>
							<tr>
								<th><%= order.created_at.strftime('%Y/%m/%d') %></th>
								<td>
									<%= order.postal_code %><br>
									<%= order.address %><br>
									<%= order.name%>
								</td>
								
								<td><% order.order_details.each do |order_detail| %>
								<%= order_detail.product.name%><% end %></td>
								
								<td><%= order.total_payment%></td>
								<td><%= order.status %></td>
								<td><%= link_to '表示する', order_path(order), class: "btn btn-primary" %></td></td>
							</tr>
							<% end %>
						</tbody>
					</table>

			</div>
    </div>
  </div>

app/views/customers/orders/new.html.erb
<div class="container">
  <div class="col-xs-offset-1 col-xs-11"><br><br><br><br>
    <h2>注文情報入力</h2>
        <%= form_with model: @order, url:customers_complete_path, local: true  do |f| %>
          <h4><b>支払い方法</b></h4>
            <label><%= f.radio_button :payment_methods, "クレジットカード", checked: true %>クレジットカード</label><br>
            <label><%= f.radio_button :payment_methods, "銀行振込" %>銀行振込</label>
          <h4><b>お届け先</b></h4>
            <label><%= f.radio_button :addresses, "myaddress", checked: true %>ご自身の住所</label><br>
            <%= "#{current_customer.postal_code} #{current_customer.address}" %>
            <br>
            <%= "#{current_customer.first_name} #{current_customer.last_name}" %>

            <div class="form-check">
            <label><%= f.radio_button :addresses, "shipping_addresses", checked: true %>登録済住所から選択</label><br>
          </div>
	          	<%= f.collection_select(:address_id, @addresses, :id, :address) %><br>


          <label><%= f.radio_button :addresses, "new_address", checked: true %>新しいお届け先</label>
            <div class="field form-group col-xs-11">
              <%= f.label :"郵便番号(ハイフンなし)", class: "col-sm-4 control-label" %>
              <%= f.text_field :postal_code, class: "col-sm-3 form-control-static postal_code" %>
            </div>
            <div class="field form-group col-xs-11">
              <%= f.label :"住所", class: "col-sm-4 control-label" %>
              <%= f.text_field :address, class: "col-sm-8 form-control-static address" %>
            </div>
            <div class="field form-group col-xs-11">
              <%= f.label :"宛名", class: "col-sm-4 control-label" %>
              <%= f.text_field :name, class: "col-sm-3 form-control-static postal_code" %>
            </div>


          <%= f.submit "確認画面へ進む", class: "btn btn-primary col-xs-4 col-xs-offset-1" %>
        <% end %>
			</div>
    </div>

app/views/customers/orders/show.html.erb
<div class="container">
        <div class="col-xs-5"><br>
          <h2>注文履歴詳細</h2>
        </div>
      </div>
      <div class="container">
        <table>
          <tr>
            <td><h3>注文情報</h3></td>
          </tr>
        </table>
            <table class="table table-bordered">
            <tr>
              <th>注文日</th>
              <th><%= @orders.created_at.strftime('%Y/%m/%d') %></th></th>
            <tr>
              <th>配送先</th>
              <th><%= @orders.postal_code %><%= @orders.address %><br></th>
            </tr>
            <tr>
              <th>支払方法</th>
              <th><%= @orders.payment_methods %></th>
            </tr>
            <tr>
              <th>ステータス</th>
              <th><%= @orders.status %></th>
            </tr>
            </table>
      </div>
      <div class="col-xs-7">
        <table>
          <tr>
            <td><h3>請求情報</h3></h3></td>
          </tr>
        </table>
            <table class="table table-bordered">
            <tr>
              <th>商品合計</th>
              <th><%= @totalprice.to_s(:delimited) %></th></th></th>
            <tr>
              <th>配送料</th>
              <th><%= 800 %><br></th>
            </tr>
            <tr>
              <th>ご請求額</th>
              <th><%= (@orders.total_payment + 800).to_s(:delimited)%></th>
            </tr>
            </table>
            <table class="table table-hover table-bordered  table-condensed">
						<thead>
							<tr>
								<th>商品</th>
								<th>単価(税込)</th>
								<th>個数</th>
								<th>小計</th>
							</tr>
						</thead>
						<tbody>
							<% @cart_products.each do |cart_product| %>
							<tr>
								<th><%= cart_product.product.name%></th></th>
								<td><%= cart_product.product.price %></td></td>
								<td><%= cart_product.quantity %></td></td>
								<td><%= (cart_product.product.price * cart_product.quantity).to_s(:delimited) %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
</div>

app/views/customers/orders/thanx.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-11"><br><br><br><br>
    <h2 class="thanx1">ご購入ありがとうございました！</h2>
  </div>
</div>