config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions: 'customer/sessions',
  passwords: 'customer/passwords',
  registrations: 'customer/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'customers/products#top'

  scope module: :customers do
  resources :products, only: [:show,:index]


  #resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy]

  get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  resources :orders, only: [:new, :create, :index, :show]

  delete 'cart_products' => 'cart_products#destroy_all', as: 'destroy_all'

  get 'product/about' => 'products#about', as: 'about'
  resources :products, only: [:show,:index], module: 'customers'
 # resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy,:destroy_all]
  resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]

  get 'searches' => 'search#search', as: 'search'

  get 'searches/products' => 'search#products', as: 'products_search'
  
  resources :customers do
    collection do
    get :quit
    patch :withdraw
  end



end
end
  namespace :customers do
    post 'orders/complete' => 'orders#complete', as: 'complete'
    #get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  end

  devise_for :admins, controllers: {
  sessions: 'admin/sessions',
  passwords: 'admin/passwords',
  registrations: 'admin/registrations'
  }
  namespace :admins do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :products, only:[:index, :new, :show, :edit, :create, :update]
    get 'top' => 'products#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :end_users, only: [:index, :show, :edit, :update]

  get 'searches' => 'search#search', as: 'search'

  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord

  # # ステータス: active (本登録), resign (退会).
  # enum is_deleted: {"有効": false, "退会済み": true}

  # customer = Customer.active.first!

  # # status を確認.
  # customer.status # => "active"

  # # status を 2 (resign) に変更!
  # customer.resign!

  # # status の取る値を確認.
  # Customer.statuses # => {"active"=>1, "resign"=>2}

end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_end_user_path, notice: ''
    else
      render 'edit'
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
    end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/views/admins/end_users/edit.html.erb
 <div class="container">
    <table>
      <tr>
        <td><h2><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h2></td><br><br><br><br>><br><br><br>
      <tr>
    </table>
    <%= form_with model: @customer, url: admins_end_user_path(@customer), local: true do |f| %>
    <table>
      <tr>
        <th><%= f.label :会員ID %></th>
        <th><%= @customer.id %></th>
      </tr>
      <tr>
        <th><%= f.label :名前（姓）%></th>
        <th><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></th>
        <th><%= f.label :（名）%></th>
        <th><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></th>
      </tr>
      <tr>
        <th><%= f.label :フリガナ（セイ） %></th>
        <th><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %></th>
        <th><%= f.label :（メイ）%></th>
        <th><%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %></th>
      </tr>
        <th><%= f.label :メールアドレス%></th>
        <th><%= f.email_field :email, autofocus: true, autocomplete: "email" %></th>
      <tr>
        <th><%= f.label :郵便番号（ハイフンなし）%></th>
        <th><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %></th>
      </tr>
      <tr>
        <th><%= f.label :住所%></th>
        <th><%= f.text_field :address, autofocus: true, autocomplete: "address" %></th>
      </tr>
      <tr>
        <th><%= f.label :電話番号（ハイフンなし）%></th>
        <th><%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %></th>
      </tr>
      <tr>
        <th><%= f.label :会員ステータス %></th>
        <th><label><%= f.radio_button :is_deleted, "有効" %>有効</label></th>
        <th><label><%= f.radio_button :is_deleted, "退会済み" %>退会済み</label></th>
      </tr>
      <tr>
        <div class="container">
          <th><%= f.submit '変更を保存する', class: "btn btn-primary" %></th>
        </div>
      </tr>
    <% end %>
  </div>

app/views/admins/end_users/index.html.erb
<div class="col-xs-9"><br><br><br>
    <h2>会員一覧</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      <div class="table">
        <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to admins_end_user_path(customer) do %><%= customer.first_name %><%= customer.last_name %><% end %></td>
          <td><%= customer.email %></td>
          <td><%= customer.is_deleted %></td>
        </tr>
        <% end %>
        <tbody>
       </div>
    </table>
  </div>
</body>

app/views/admins/end_users/show.html.erb
  <div class="container"><br><br><br><br><br>
    <table>
      <tr>
        <td><h2><%= @customer.first_name %> <%= @customer.last_name %>さんの会員詳細</h2></td><br><br>
      <tr>
    </table>
    <table>
      <tr>
        <th>会員ID</th>
        <th><%= @customer.id %></th>
        <% if @customer.is_deleted == "有効" %>
          <th><button type="button" class="btn btn-primary">有効会員</button><th>
        <% else %>
          <th><button type="button" class="btn btn-primary">退会済み</button><th>
        <% end %>
      </tr>

      <tr>
        <th>氏名</th>
        <th><%= @customer.first_name %> <%= @customer.last_name %></th>
      </tr>
        <th>フリガナ</th>
        <th><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></th>
      </tr>
      <tr>
        <th>郵便番号</th>
        <th><%= @customer.postal_code %></th>
      </tr>
      <tr>
        <th>住所</th>
        <th><%= @customer.address %></th>
      </tr>
      <tr>
        <th>電話番号</th>
        <th><%= @customer.telephone_number %></th>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <th><%= @customer.email %></th>
      </tr>
    </table>
    <br><br>
    <tr>
       <th><%= link_to "編集する", edit_admins_end_user_path, class: 'btn btn-primary' %></th>
    </tr>
    <tr>
       <th><%= link_to "注文履歴を見る", admins_orders_path, class: 'btn btn-primary' %></th>
    </tr>
  </div>