config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions: 'customer/sessions',
  passwords: 'customer/passwords',
  registrations: 'customer/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'customers/products#top'

  scope module: :customers do
  resources :products, only: [:show,:index]


  #resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy]

  get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  resources :orders, only: [:new, :create, :index, :show]

  delete 'cart_products' => 'cart_products#destroy_all', as: 'destroy_all'

  get 'product/about' => 'products#about', as: 'about'
  resources :products, only: [:show,:index], module: 'customers'
 # resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy,:destroy_all]
  resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]

  get 'searches' => 'search#search', as: 'search'

  get 'searches/products' => 'search#products', as: 'products_search'
  
  resources :customers do
    collection do
    get :quit
    patch :withdraw
  end



end
end
  namespace :customers do
    post 'orders/complete' => 'orders#complete', as: 'complete'
    #get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  end

  devise_for :admins, controllers: {
  sessions: 'admin/sessions',
  passwords: 'admin/passwords',
  registrations: 'admin/registrations'
  }
  namespace :admins do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :products, only:[:index, :new, :show, :edit, :create, :update]
    get 'top' => 'products#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :end_users, only: [:index, :show, :edit, :update]

  get 'searches' => 'search#search', as: 'search'

  end
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :cart_product, dependent: :destroy

  attachment :image
  has_many :order_details, dependent: :destroy

  belongs_to :genre
  enum is_active: { 売り切れ: false, 販売中: true }

  def self.search(method,word)
    if method == "perfect_match"
      Product.where("name = ?", word)
    elsif method == "partial_match"
      Product.where("name LIKE ?","%#{word}%")
    end
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

 def index
 end

 def show
 end

 def edit
 end

 def update
 end

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end

  def index
    @product = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    @product.save!
    redirect_to admins_products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admins_products_path, notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def product_params
    params.require(:product).permit( :image, :name, :introduction, :price, :genre_id, :is_active )
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
   before_action :reject_customer, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end




  protected

  def reject_customer

    if @customer = Customer.find_by(email: params[:customer][:email])
      if @customer.is_deleted == "退会済み"
        flash[:error] = "退会済みです。"
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def new
    @address = Address.new
  end

  def index
    @address = Address.new
    @addresses = current_customer.addresses
    # @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save!
    redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
     @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to  addresses_path, notice: ''
    else
      render 'edit'
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customers/cart_products_controller.rb
class Customers::CartProductsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_product = current_customer.cart_products
    if @cart_product.empty?
       @totalprice = 0
    else
       @totalprice = @cart_product.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+).to_s(:delimited)
    end
  end

  def create
    @cart_product = CartProduct.new(cart_product_params)
    @cart_product.customer_id = current_customer.id
    if @cart_product.save
    redirect_to cart_products_path
    else
      @product = Product.find(params[:cart_product][:product_id])
      @genres = Genre.all
      render 'customers/products/show'
    end
  end
  def update
    @cart_product = CartProduct.find(params[:id])
    if @cart_product.update(cart_product_params)
      redirect_to cart_products_path, notice: ''
    else
      render 'index'
    end
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to cart_products_path
  end

  def destroy_all
    @cart_product = current_customer.cart_products
    @cart_product.destroy_all
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to cart_products_path
  end

  private
    def cart_product_params
       params.require(:cart_product).permit(:product_id, :quantity)
    end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
     @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path, notice: ''
    else
      render 'edit'
    end
  end

  def withdraw
    current_customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def self.search(word)
  end

 private
    def customer_params
       params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
    end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  def new
    @order = Order.new
    @addresses = Address.all
  end

  def create
    @cart_products = current_customer.cart_products

    @order = Order.new(order_params)
    if params[:addresses] == "new_address"
      @address = Address.new
      @address.postal_code = @order.postal_code
      @address.address     = @order.address
      @address.name        = @order.name
      @address.customer_id = current_customer.id
      @address.save
    end

    if @order.save

    @cart_products.each do |cart_product|
      @order_detail = OrderDetail.new
      @order_detail.amount = cart_product.quantity
      @order_detail.price = cart_product.product.price
      @order_detail.order_id = @order.id
      @order_detail.product_id = cart_product.product.id
      @order_detail.save
    end
    redirect_to thanx_path
    else
      render '/customers/orders/complete'
    end

  end


  def complete
    @cart_products = current_customer.cart_products
    @totalprice = @cart_products.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+)
    @order = Order.new
    @order.customer_id = current_customer.id
    @order.total_payment = @totalprice
    if params[:order][:addresses] == "myaddress"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.address
      @order.name        = current_customer.last_name +
                          current_customer.first_name
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name
    elsif params[:order][:addresses] == "new_address"
      # @address = Address.new
      # @adress.postal_code = params[:order][:postal_code]
      # @adress.address     = params[:order][:address]
      # @adress.name        = params[:order][:name]
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

    end

  end

  def thanx
  end

  def index
    @orders = Order.all
    @cart_products = current_customer.cart_products
    @order_detail = current_customer.cart_products
  end

  def show
    @cart_products = current_customer.cart_products
    @totalprice = @cart_products.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+)
    @orders = Order.find(params[:id])
  end

  def thanx
  end


  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :payment_methods, :name, :total_payment, :shipping_cost, :status, :customer_id,  :address_id, :addresses )
  end

end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
  def top
    @product = Product.page(params[:page]).reverse_order
    @genres = Genre.all
  end

  def about
  end

  def index
    if params[:genre_id]
       @product = Product.where(genre_id: params[:genre_id]).page(params[:page]).reverse_order
       @genre_name = Genre.find(params[:genre_id]).name
    else
       @product = Product.page(params[:page]).reverse_order
       @genre_name = "商品"
    end
    @genres = Genre.all
  end

  def show
     @product = Product.find(params[:id])
     @cart_product = CartProduct.new
     @genres = Genre.all
  end
end

app/controllers/customers/search_controller.rb
class Customers::SearchController < ApplicationController
  before_action :authenticate_customer!

	def search
		@word = params[:search_word]
		method = params[:search_method]
		# model = params[:search_model]
		@products = Product.search(method,@word)
		# if model == 'Product'
	 #   @products = Product.search(method,@word)
	 # else
	 #   @products = Product.all
	 # end
	end

  def products
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @value).page(params[:page]).reverse_order
    @genres = Genre.all


    @genre = Genre.find_by(name: @value)

  end

  private

  def match(value)

    Product.where(name: value).or(Product.where(genre_id: value))
  end

  def forward(value)
    Product.where("name LIKE ?", "#{value}%")
  end

  def backward(value)
    Product.where("name LIKE ?", "%#{value}")
  end

  def partical(value)
    Product.where("name LIKE ?", "%#{value}%")
  end


  def search_for(how, value)
    case how
    when 'match'
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
     @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path, notice: ''
    else
      render 'edit'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_path
  end

 private
    def customer_params
       params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
    end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/products/about.html.erb
<div class="row1">
<div class="parallax-bg"></div>
  <h1  class="about1">About</h1>
  <br>
  <div class="scrollbox">
  <p class="p1">ながのCakeは全国発送可能なケーキ屋さんです。</p><br>
  <p class="p1">お子様からお年寄りの方までお召し上がりいただけるよう、</p><br>
  <p class="p1">様々なバリエーションをご用意しております。</p><br>
  <p class="p1">また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。</p><br>
  <p class="p1">ぜひご注文ください。</p></div><br>
  <div class="parallax-bg"></div>
</div>

app/views/customers/products/index.html.erb
<div class="row4">
  <div class="col-xs-3">
    <div class="name-search">
  <% if customer_signed_in? %>                       
    <h5>商品名検索</h5>
    <%= form_with url: products_search_path, method: :get, local: true do |f| %>
      <%= f.text_field 'search[value]', size: "26x4" %><br>
      <span class="search-button col-xs-12 text-right">
        <%= f.select 'search[how]', options_for_select({ "部分一致" => "partical", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "match" }) %>
        <%= f.submit :"検索" %>
      </span>
    <% end %>
  <% end %>
</div>
<table class="table table-bordered genre-table">
    <thead>
      <tr>
        <th>ジャンル検索</th>
      </tr>
    </thead>
    <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td>
          <%= link_to genre.name, products_path(genre_id: genre.id) %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>
  </div>
  
  <div class="col-xs-9">
    <h1>
      <strong><%= @genre_name %>一覧</strong> (全<%= @product.count %>件)
    </h1>
    <div class="">
      <% @product.each_with_index do |product, idx| %>
      <% if (idx+1)%3==0 %>
        <div class="row">
          <% end %>
        <div class="col-xs-4 item-card" >
      		<div class="image11"><%= attachment_image_tag product, :image, size:'200x170' %></div>
      		<div class="name11"><%= link_to product.name,product_path(product.id) %></div>
          <div class="image11">¥<%= product.price %></div>
        </div>
        <% if (idx+1)%3==0 %>
        </div>
          <% end %>
      <% end %>
    </div>
  </div>
  <%= paginate @product %>

app/views/customers/products/show.html.erb
<div class="row4">
  <div class="col-xs-3">
    <div class="name-search">
  <% if customer_signed_in? %>                       
    <h5>商品名検索</h5>
    <%= form_with url: products_search_path, method: :get, local: true do |f| %>
      <%= f.text_field 'search[value]', size: "26x4" %><br>
      <span class="search-button col-xs-12 text-right">
        <%= f.select 'search[how]', options_for_select({ "部分一致" => "partical", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "match" }) %>
        <%= f.submit :"検索" %>
      </span>
    <% end %>
  <% end %>
</div>
<table class="table table-bordered genre-table">
    <thead>
      <tr>
        <th>ジャンル検索</th>
      </tr>
    </thead>
    <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td>
          <%= link_to genre.name, products_path(genre_id: genre.id) %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>
  </div>
  
 
  <%= form_with model:@cart_product, url:cart_products_path,  method: :post, local:true do |f| %>
      <br><br><br><br><br>
      <div class="col-xs-3">
      <%= attachment_image_tag @product, :image, size:'330x270' %>
      </div>
      <div class="col-xs-6">
        <h2><strong><%= @product.name %></strong></h2>
      <br>
      <%= @product.introduction %>
      <br>
      <br>
      <h2>￥<%= @product.price %></h2><h4>（税込）</h4>
      <%= f.hidden_field :product_id, :value => @product.id %>
      <% if @cart_product.errors.any? %>
    		<div id="error_explanation">
    			<h3><%= @cart_product.errors.count %>error prohibited this obj from being saved:</h3>
    			<ul>
    				<% @cart_product.errors.full_messages.each do |message| %>
    				  <li><%= message %></li>
    				<% end %>
    			</ul>
    		</div>
	    <% end %>
      <%= f.number_field :quantity %> <%= f.submit "カートに入れる", class:"btn btn-primary" %>
      </div>
  <% end %>
  

app/views/customers/products/top.html.erb
<body>
  <% content_for(:body_attributes) do %>
    data-turbolinks="false"
<% end %>
<div class="row4">
  <div class="col-xs-3">
    <div class="name-search">
  <% if customer_signed_in? %>
    <h5　class="name22">商品名検索</h5>
    <%= form_with url: products_search_path, method: :get, local: true do |f| %>
      <%= f.text_field 'search[value]', size: "26x4" %><br>
      <span class="search-button col-xs-12 text-right">
        <%= f.select 'search[how]', options_for_select({ "部分一致" => "partical", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "match" }) %>
        <%= f.submit :"検索" %>
      </span>
    <% end %>
  <% end %>
  </div>
  <table class="table table-bordered genre-table">
    <thead>
      <tr>
        <th>ジャンル検索</th>
      </tr>
    </thead>
    <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td>
          <%= link_to genre.name, products_path(genre_id: genre.id) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
  <div class="col-xs-9">
  <div id="container">
      <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
        <div class="image4"></div>
  </div>
    <section class="product1">
      <h1>オススメ商品</h1>
      <table class="table">
        <thead></thead>
        <tbody>
          <% @product.each do |product| %>
    		    <td>
    		      <div class="image11"><%= attachment_image_tag product, :image, size:'200x170' %></div>
    		      <div class="name11"><%= link_to product.name,product_path(product.id) %></div>
              <div class="image11">¥<%= product.price %></div>
            </td>
          <% end %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td><%= link_to "もっと見る>", products_path %></td>
            </tr>
        <tbody>
      </table>
    </section>
  </div>
</div>
<%= paginate @product %>
</body>