config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions: 'customer/sessions',
  passwords: 'customer/passwords',
  registrations: 'customer/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'customers/products#top'

  scope module: :customers do
  resources :products, only: [:show,:index]


  #resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy]

  get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  resources :orders, only: [:new, :create, :index, :show]

  delete 'cart_products' => 'cart_products#destroy_all', as: 'destroy_all'

  get 'product/about' => 'products#about', as: 'about'
  resources :products, only: [:show,:index], module: 'customers'
 # resources :orders, only: [:new, :create, :index, :show]

  resources :cart_products, only: [:index,:create,:update,:destroy,:destroy_all]
  resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]

  get 'searches' => 'search#search', as: 'search'

  get 'searches/products' => 'search#products', as: 'products_search'
  
  resources :customers do
    collection do
    get :quit
    patch :withdraw
  end



end
end
  namespace :customers do
    post 'orders/complete' => 'orders#complete', as: 'complete'
    #get 'orders/thanx' => 'orders#thanx', as: 'thanx'
  end

  devise_for :admins, controllers: {
  sessions: 'admin/sessions',
  passwords: 'admin/passwords',
  registrations: 'admin/registrations'
  }
  namespace :admins do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :products, only:[:index, :new, :show, :edit, :create, :update]
    get 'top' => 'products#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :end_users, only: [:index, :show, :edit, :update]

  get 'searches' => 'search#search', as: 'search'

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum status: {"入金待ち": 0,"入金確認": 1,"制作中": 2,"発送準備中": 3,"発送済み": 4 }
  enum payment_methods: {"クレジットカード": 0,"銀行振込": 1 }
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    # @cart_products = current_customer.cart_products
    @order_details = @order.order_details
    @totalprice = @order_details.map{ |order_detail| order_detail.product.price * order_detail.amount}.inject(:+)
    #@cart_products = @order.cart_products
		#@order_detail = params[:making_status]
  end

  def index
    @orders = Order.all
    @order = params[:name]
    #@order_details = OrderDetails.all
    #@order_detail = OrdrDetail.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admins_orders_path
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

  def order_details_params
    params.require(:order_details).permit(:amount, :making_status)
  end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  def new
    @order = Order.new
    @addresses = Address.all
  end

  def create
    @cart_products = current_customer.cart_products

    @order = Order.new(order_params)
    if params[:addresses] == "new_address"
      @address = Address.new
      @address.postal_code = @order.postal_code
      @address.address     = @order.address
      @address.name        = @order.name
      @address.customer_id = current_customer.id
      @address.save
    end

    if @order.save

    @cart_products.each do |cart_product|
      @order_detail = OrderDetail.new
      @order_detail.amount = cart_product.quantity
      @order_detail.price = cart_product.product.price
      @order_detail.order_id = @order.id
      @order_detail.product_id = cart_product.product.id
      @order_detail.save
    end
    redirect_to thanx_path
    else
      render '/customers/orders/complete'
    end

  end


  def complete
    @cart_products = current_customer.cart_products
    @totalprice = @cart_products.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+)
    @order = Order.new
    @order.customer_id = current_customer.id
    @order.total_payment = @totalprice
    if params[:order][:addresses] == "myaddress"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.address
      @order.name        = current_customer.last_name +
                          current_customer.first_name
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name
    elsif params[:order][:addresses] == "new_address"
      # @address = Address.new
      # @adress.postal_code = params[:order][:postal_code]
      # @adress.address     = params[:order][:address]
      # @adress.name        = params[:order][:name]
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

    end

  end

  def thanx
  end

  def index
    @orders = Order.all
    @cart_products = current_customer.cart_products
    @order_detail = current_customer.cart_products
  end

  def show
    @cart_products = current_customer.cart_products
    @totalprice = @cart_products.map{|cart_product|cart_product.product.price * cart_product.quantity}.inject(:+)
    @orders = Order.find(params[:id])
  end

  def thanx
  end


  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :payment_methods, :name, :total_payment, :shipping_cost, :status, :customer_id,  :address_id, :addresses )
  end

end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/orders/index.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-11"><br><br><br><br><br><br>
    <h2>注文履歴一覧</h2>
      <div class="col-xs-6 col-xs-offset-1">
        <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>購入日時</th></th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td class="text-left">
              <%= link_to admins_order_path(order) do %>
                <%= order.created_at %>
              <% end %>
              </td>
              <td class="order-td"><%= order.name %>様</td>


              <td class="order-td"><%= order.order_details.pluck(:amount).sum %>
                <!--%= order.order_details.count % -->
                <!--% order.order_details.each do |order_detail| %>
                    % order_detail.amount %>% end %-->
              </td></td>

              <td class="order-td"><%= order.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-11"><br><br><br><br>
    <h2>注文履歴詳細</h2>
      <div class="col-xs-6 col-xs-offset-1">
        <div class="container-fluid">
	        <div class="row">
		        <div class="col-md-4">購入者</div>
		        <div class="col-md-8"><%= @order.name %></div>

		        <div class="col-md-4">配送先</div>
		        <div class="col-md-8">〒<%= @order.postal_code %><%= @order.address %><br><%= @order.name %></div>

		        <div class="col-md-4">支払い方法</div>
		        <div class="col-md-8"><%= @order.payment_methods %></div>

						<%= form_for(@order, url: admins_order_path, method: :patch) do |f| %>
		        <div class="col-md-4">注文ステータス</div>
              <%= f.select :status, Order.statuses.keys.map{ |k| k } %>
			            <td>
			            	<!--%= f.select :making_status, OrderDetail.making_statuses.keys, class: "making_status" %>-->
			            	<%= f.submit '更新'  ,class: "btn btn-warning" %>
			            </td>
			       <% end %>
		        <!--<div class="col-md-8">%= f.submit '更新' ,class: "btn btn-primary" %--></div>

	        </div>
        </div>
        <div class="col-xs-6 col-xs-offset-1">
        <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>商品名</th></th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <% @order_details.each do |order_detail| %>
            <tr>
              <td class="text-left">
                <%= order_detail.product.name %>
              </td>
              <td class="text-right">
                <%= order_detail.product.price %>
              </td>
              <td class="text-right">
                <%= order_detail.amount %>
              </td>
              <td class="text-right">
                <%= (order_detail.product.price * order_detail.amount).to_s(:delimited) %>
              </td>
              <td class="text-right">
                <%= form_for(order_detail, url: admins_order_detail_path(order_detail.id), method: :patch) do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map{ |k| k } %>
                    <td>
                      <%= f.submit '更新'  ,class: "btn btn-warning" %>
                    </td>
			          <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-5">
      <h4>
        <strong>商品合計</strong>　<%= @totalprice.to_s(:delimited) %>円
      </h4>
      <h4>
        <strong>送料</strong>      800円
      </h4>
      <h4>
        <strong>請求金額合計      <%= (@totalprice + 800).to_s(:delimited) %>円</strong>
      </h4>
    </div>
  </div>
</div>